# Site settings
title:
  en: My bilingual blog
  es: Mi blog bilingüe

email: some.one@gmail.com

# Dependencies (adjust as required)
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# Permalinks
permalink:        pretty
